-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Gazdă: localhost
-- Timp de generare: mai 27, 2020 la 02:27 AM
-- Versiune server: 10.4.11-MariaDB
-- Versiune PHP: 7.4.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Bază de date: `gamadb`
--

-- --------------------------------------------------------

--
-- Structură tabel pentru tabel `infogames`
--

CREATE TABLE `infogames` (
  `id_joc` int(11) NOT NULL,
  `nr_jucatori` varchar(100) NOT NULL,
  `dificultate` varchar(100) NOT NULL,
  `varsta` varchar(100) NOT NULL,
  `timp_de_joc` varchar(1000) NOT NULL,
  `descriere` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Eliminarea datelor din tabel `infogames`
--

INSERT INTO `infogames` (`id_joc`, `nr_jucatori`, `dificultate`, `varsta`, `timp_de_joc`, `descriere`) VALUES
(1, '1-5', ' medium', '8+', '40-70 min', 'Wingspan is a competitive, medium-weight, card-driven, engine-building board game from Stonemaier Games. You are bird enthusiasts—researchers, bird watchers, ornithologists, and collectors—seeking to discover and attract the best birds to your network of wildlife preserves. Each bird extends a chain of powerful combinations in one of your habitats (actions).'),
(2, '2+', 'medium', '14+', '30-50 min', 'Blinded by Science is for people who understand the meaning of deoxyribonucleic acid. Curie, Darwin, Galileo, Tesla, Turing...if these are some of your heroes, then this game is for you! Each card covers a different scientific subject, and includes three questions with increasing degrees of difficulty. If you\'re a trivia buff and science is your thing, then this game is probably in your DNA.'),
(3, '2-5', '2.50/5', '10+', '60-90 min', 'Cytosis: A Cell Building Game is a worker placement game that takes place inside a human cell. Players start out with a number of workers and on a player’s turn, they will place one of their workers in any available location within that cell. Some of the locations provide players with resources (e.g., mRNA, ATP); some with actions (e.g., convert resources, collect cards). Resources are used to build enzymes, hormones and/or receptors, which score Health Points. The player with the most Health Points at the end of the game wins!'),
(4, '2-5', '2.50/5', '10+', '60-90 min', 'The simple strategy game at the core of Evo is made more interesting by the constantly changing climate. Positions which can be advantageous in one turn are often deadly a few turns later, so unlike many games where a winning player can come to dominate the game, the balance of power shifts frequently.'),
(5, '2-4', '2/5', '15+', '30-45 min', 'Throughout the centuries, mad scientists have always encountered the same problem of very limited access to the dangerous resources they require. To solve this problem, the Mad Science Foundation was created. Now these \"misunderstood geniuses\" can finally get the access they need to the four vital building blocks of mad science: Lasers, Dark Matter, Cryptomium, and Sharks.'),
(6, '2-8', '2/5', '7+', '30 min', 'Professor Noggin takes Science out of the classroom and into this entertaining trivia game. See what you know, and learn surprising new facts as you go. Wonders of Science will create science wonderment for all who play.Players take turns rolling the die and asking each other questions from the cards. If a question is answered correctly, the card is won; if answered incorrectly, the card is returned to the bottom of the pile. The player with the most cards at the end of the game is the winner. Players have a few chances throughout the game to get a Noggin\'s Choice card. This means they can choose a card from any other player, and get ahead. Remember the correct answers. If a question is not answered correctly the first time, that question will come up again.'),
(7, '3-6', '2/5', '9+', '40-50 min', 'Keep Cool is a board game created by Klaus Eisenack and Gerhard Petschel-Held of the Potsdam Institute for Climate Impact Research and published by the German company Spieltrieb in November 2004. The game can be classified as both a serious game and a global warming game. In Keep Cool, up to six players representing the world\'s countries compete to balance their own economic interests and the world\'s climate in a game of negotiation. The goal of the game as stated by the authors is to \"promote the general knowledge on climate change and the understanding of difficulties and obstacles, and \"to make it available for a board game and still retain the major elements and processes.\" Empirical studies have shown that Keep Cool can facilitate experiential learning about the difficulties of international climate politics.'),
(8, '2-6', '1/5', '5+', '60 min', 'The UNGAME was designed for YOU to experience the fun of learning how to communicate more effectively. As you share thoughts, ideas and feelings, you will develop a deeper understanding of others and of yourself. Each person\'s ability to respond and become involved will improve as he continues to TELL IT LIKE IT IS. You\'ll find the UNGAME both entertaining AND educational.'),
(9, ' 2-5', '2/5', '12+', '60 min', 'The board game Kolejka (a.k.a. Queue) tells a story of everyday life in Poland at the tail-end of the Communist era. The players\' task appears to be simple: They have to send their family members out to various stores on the game board to buy all the items on their shopping list. The problem is, however, that the shelves in the five neighborhood stores are empty.'),
(10, ' 2-4', '2/5', '8+', '120 min', '\"Scrabble with math\" is how this game is generally described, and the description is apt. The board is much like a Scrabble board, including spaces equivalent to \"double-word score\" and \"triple-letter score\". The difference is that, instead of placing words formed of letters, players of Equate place equations formed of numbers and symbols on the board. The beginners game (consisting mostly of addition and subtraction of integers) is pretty simple, but the standard game, bringing in multiplication, division, and fractions, can be something of a brain-burner.'),
(11, '2', '1.5/5', '9+', '60 min', 'Battle Masters is a fantasy miniatures battle game by Milton Bradley, presumably licensed from Games Workshop. The sizeable game box comes stuffed with tons of plastic miniatures, a deck of combat cards and some dice. Players move and fight their armies based upon what card is turned over from the deck. Combat is held on a large vinyl mat 4.5 ft square'),
(12, '2-4', '4.5/5', '11+', '90 min', 'Blood Bowl: Team Manager - The Card Game is a bone-breaking, breathtaking standalone card game of violence and outright cheating for two to four players. Chaos, Dwarf, Wood Elf, Human, Orc, and Skaven teams compete against each other over the course of a brutal season. Customize your team by drafting Star Players, hiring staff, upgrading facilities, and cheating like mad. Lead your gang of misfits and miscreants to glory over your rivals all to become Spike! Magazine s Manager of the Year!'),
(13, '2', '1.5/5', '11+', '80 min', 'Escape from Atlantis is similar to the Parker Brothers game Survive! but with some key differences (e.g., people pawns are not worth a variable number of points). In 2010, a reworked version of Escape from Atlantis which combines the rules of the game along with the rules to Survive! was printed by Stronghold Games titled \"Survive: Escape from Atlantis!\"'),
(14, '4', '1.5/5', '9+', '45 min', 'A game created by Games Workshop in the mid 80s that puts each player in the position of being an orcish general who must muster his troops into three battle lines in preparation of attacking the dwarves. Each player begins with a blank card mat which is slowly filled with cards that represent different units of orcs, goblins, war machines, and treasure. Each card has its own rules which affect play.'),
(15, '5-6', '3/5', '9+', '50-60 min', 'Dark Tower was technologically impressive when it was released in 1981. Gameplay was facilitated by a small computer inside the black plastic shell of the tower itself. Players input their moves on a small membrane keypad each turn and the computer took over from there, doing everything from conducting the progress of battles to keeping track of how much (or little) food was left to feed the players always hungry warriors. The computer would play brief musical serenades at significant points of the game.'),
(16, '3-4', '2.5/5', '7+', '45 min', '7 Days of Westerplatte is a cooperative war game. The players incorporate the roles of Polish commanders who work together to confront the German army and win the game. Stukas s raids, land troop attacks, and battleship and howitzer bombardments are the biggest threat for Polish forces, and to hold back the attacking German troops, players must use land mines, mortars and rifles, while also remembering to rebuild the defensive structures and keep their morale high. Will you manage to defend the Depot for seven days, or will you succumb to the enemy s crushing power?'),
(17, '8-9', '1.5/5', '8+', '45-60 min', 'It depicts WWII on a grand scale, full global level. Up to five players can play on two different teams. The Axis which has Germany and Japan, and the Allies which has the USA, the United Kingdom, and the USSR. A full map of the world is provided, broken up in various chunks similar to Risk. The game comes with gobs of plastic miniatures that represent various military units during WWII.'),
(18, '4-6', '1.5/5', '10+', '60-80 min', 'In 1413, the new king of England, Henry V of Lancaster, has ambitious plans: The unification of England and the conquest of the French crown! Each player takes the role of an ambitious aristocratic family. Who will be the best supporter of this young king, and the most powerful Lord of his time?'),
(20, '7-8', '5/5', '9+', '120-150 min', 'Carcassonne is a tile-placement game in which the players draw and place a tile with a piece of southern French landscape on it. The tile might feature a city, a road, a cloister, grassland or some combination thereof, and it must be placed adjacent to tiles that have already been played, in such a way that cities are connected to cities, roads to roads, etcetera.'),
(21, '8-9', '4.5/5', '10+', '60-70 min', 'In 1960: The Making of the President, you take on the role of one of these great protagonists vying for the right to lead his country into the heart of the Cold War. However, it is not just foreign policy that poses a challenge to American leadership; this is also an era of great social turmoil and progress.'),
(22, '7-8', '3.5/5', '10+', '50-60 min', 'The \"Stone Age\" times were hard indeed. In their roles as hunters, collectors, farmers, and tool makers, our ancestors worked with their legs and backs straining against wooden plows in the stony earth. Of course, progress did not stop with the wooden plow. People always searched for better tools and more productive plants to make their work more effective. In Stone Age, the players live in this time, just as our ancestors did.'),
(23, '4-5', '1.5/5', '9+', '45 min', 'Welcome to the experiential table top game that is going to redefine what it means to play a game. Nyctophobia, which means \"fear of the dark\", is a cooperative game of survival in which up to four players must work together to escape a maniacal predator chasing them in a pitch-black forest. But there s a wrinkle: Would-be survivors play the game with blackout glasses. Players cannot see the board and have to rely on touch to navigate their way to safety. So, are you afraid of the dark?'),
(24, '6-7', '3.5/5', '11+', '50-60 min', 'Betrayal at House on the Hill quickly builds suspense and excitement as players explore a haunted mansion of their own design, encountering spirits and frightening omens that foretell their fate. With an estimated one hour playing time, Betrayal at House on the Hill is ideal for parties, family gatherings or casual fun with friends.'),
(25, '4', '1.5/5', '11+', '45-65 min', 'Zombicide is a collaborative game in which players take the role of a survivor – each with unique abilities – and harness both their skills and the power of teamwork against the hordes of unthinking undead! Zombies are predictable, stupid but deadly, controlled by simple rules and a deck of cards. Unfortunately for you, there are a LOT more zombies than you have bullet'),
(26, '4-7', '4/5', '9+', '45 min', 'The lightning fast shape and color recognition game that is sure to test the reflexes of kids, families and gamers alike. In Ghost Blitz, five wooden items sit on the table waiting to be caught: a white ghost, a green bottle, a cute grey mouse, a blue book, and a comfortable red chair. Each card in the deck shows pictures of two objects, with one or both objects colored the wrong way. With all players playing at the same time, someone reveals a card, then players grab for the \"right\" object – but which object is right?'),
(27, '6-7', '1.5/5', '10+', '60-90 min', 'Dead of winter puts players in a small colony of survivors who must work together towards group victory, but at the same time, players must also complete a personal objective to win as individuals. Players often have to decide what’s best for the colony and best for themselves, which creates high-stakes gameplay.'),
(28, '4-5', '3.5/5', '9+', '80 min', 'Mansions of Madness: Second Edition is a fully cooperative, app-driven board game of horror and mystery for one to five players that takes place in the same universe as Eldritch Horror and Elder Sign. Let the immersive app guide you through the veiled streets of Innsmouth and the haunted corridors of Arkham s cursed mansions as you search for answers and respite.'),
(29, '2', '2.5/5', '10+', '20 min', '0 DAY ATTACK ON EARTH is designed as a twin-stick shooter in its core, where the movement is done with the left stick and shooting with the right.There is a main goal in each level, which is to take down a certain number of boss aliens before a timer goes down to zero. However, the skies are also filled with smaller ships, and there are pods and snakes that burst from the ground. Aiding the fight against the enemies are power-ups like spray gun and flame throwers, as well as special abilities like nitro boost that helps moving the ship out of any harm.0 Day Attack on Earth consists of 28 levels that are split in groups of seven that take place in four cities.Each city is accurately depicted through satellite imagery,containing landmarks like Champs-Élysées, Tokyo Tower, and Arc de Triomphe. One of the features included is co-op play for up to four players (when playing offline, AI-controlled ships will support the player instead). Besides co-op, there are Capture the Flag and Capture Point multiplayer modes.'),
(30, '4', '1.5/5', '9+', '45 min', 'Most games in the Bomberman franchise largely revolve around two modes of play; single player campaigns where the player must defeat enemies and reach an exit to progress through levels, and multiplayer modes where players must attempt to eliminate each other and be the last one standing. Gameplay involves strategically placing down bombs, which explode in multiple directions after a certain amount of time, in order to destroy obstacles and kill enemies and other players. The player can pick up various power-ups, giving them benefits such as larger explosions or the ability to place more bombs down at a time. The player is killed if they touch an enemy or get caught up in a bomb s explosion, including their own, requiring players to be cautious of their own bomb placement. In addition to the main maze-based Bomberman games, some spin-off titles involve adventure, platformer, puzzle, and kart racing gameplay.'),
(31, '2-3', '1.5/5', '12+', '10-15 min', '10.000Bulets: is a worker placement game that takes place inside a human cell. Players start out with a number of workers and on a player’s turn, they will place one of their workers in any available location within that cell. Some of the locations provide players with resources (e.g., mRNA, ATP); some with actions (e.g., convert resources, collect cards). Resources are used to build enzymes, hormones and/or receptors, which score Health Points. The player with the most Health Points at the end of the game wins!'),
(32, '2', '3.5/5', '10+', '10 min', 'is an action-adventure game set within an open world Gotham City, which can be explored freely by the player from the beginning of the game, allowing them to travel seamlessly anywhere within its boundaries. Many of the gadgets and the gameplay elements from the previous Arkham games return, including the grapnel gun, line launcher, batarangs, the countering system, Detective Vision, and the Remote Hacking Device'),
(33, '1', '5/5', '6+', '10-15 min', 'In Mario , the player takes on the role of Mario, the protagonist of the series. Mario s younger brother, Luigi, is controlled by the second player in the game s multiplayer mode and assumes the same plot role and functionality as Mario. The objective is to race through the Mushroom Kingdom, survive the main antagonist Bowser s forces, and save Princess Toadstool.'),
(34, '2', '3.5/5', '9+', '25 min', 'The player has the view of an airstrip as seen from the cockpit of a jet fighter. In order to start the launch, it is required that the player presses the fire button. When the player pulls back on the joystick, the jet fighter becomes airborne. A feature of the game includes a horizontal tilt that happens when the jet fighter turns to the left or the right for realistic simulation. The goal is to fire at enemy aircraft. The player also has to worry about not making a quick dive after an enemy craft that would lead to a crash landing. There is also a bar that is located on the width of the screen that allows the player to keep track of the horizontal position. It is important to stay out of heavy unfire zones because it can lead to a nosedive crash. It is possible to pull out of a nosedive, but it would be a better idea for the player to avoid flak.'),
(35, '2-4', '2.5/5', '7+', '45 min', 'Apex Legends is an online multiplayer battle royale game featuring squads of three players using pre-made characters , similar to those of hero shooters. Alternate modes have been introduced allowing for single and for two-player squads since the game s release'),
(36, '4', '1.5/5', '9+', '45 min', 'Most games in the AMAZING ETERNALS franchise largely revolve around two modes of play; single player campaigns where the player must defeat enemies and reach an exit to progress through levels, and multiplayer modes where players must attempt to eliminate each other and be the last one standing. '),
(37, '2-4', '3.5/5', '10+', '25 min', 'In Quake s single-player mode, players explore and navigate to the exit of each Gothic and dark level, facing monsters and finding secret areas along the way. Usually there are switches to activate or keys to collect in order to open doors before the exit can be reached. Reaching the exit takes the player to the next level. Before accessing an episode, there is a set of three pathways with easy, medium, and hard skill levels. The fourth skill level, \"Nightmare\", was \"so bad that it was hidden, so people won t wander in by accident\"; the player must drop through water before the episode four entrance and go into a secret passage to access it.'),
(38, '2', '1.5/5', '9+', '10-15 min', 'Overwatch is an online team-based game generally played as a first-person shooter. The game features several different game modes, principally designed around squad-based combat with two opposing teams of six players each. Players select one of over two dozen pre-made hero characters from one of three class types: Damage heroes that deal most of the damage to attack or defend control points, Tank heroes that can absorb a large amount of damage, and Support heroes that provide healing or other buffs for their teammates.'),
(39, '4', '1.5/5', '9+', '45 min', 'Valorant is an upcoming free-to-play multiplayer first-person shooter developed and published by Riot Games.'),
(40, '1', '1.5/5', '7+', '45-60 min', 'Evolve is an action video game with a focus on both co-operative, and competitive, multiplayer gameplay. The game adapts a 4v1 asymmetrical structure where four players take control of the Hunters, while the fifth player controls the Monster. The Hunters  main objective is to track and hunt the Monster in a limited amount of time, while the Monster s goal is to evolve and make themselves more powerful.'),
(41, '1', '2.5/5', '9+', '30 min', 'Soccer Kid is a platform game where players take control of the titular character travelling across the world in order to retrieve and restore the world cup from the clutches of the alien pirate Scab, who plans to add it to his ever-growing collection. By pressing different buttons at the title screen, the player can change the colours of their character s clothes in order to represent their favorite team.'),
(42, '4', '1.5/5', '9+', '45 min', 'NBA 2K20 is a basketball simulation game which, like the previous games in the series, strives to realistically depict the National Basketball Association (NBA), as well as present improvements over the previous installments. The player mainly plays NBA games with real-life or customized players and teams; games follow the rules and objectives of NBA games. Several game modes are present and many settings can be customized. Up to six expansion teams can be created and used in both MyLeague and MyGM Modes, with the possibility of a 36-team league, and any team can be relocated and rebranded.'),
(43, '2', '2.5/5', '8+', '30 min', 'Rockstar Games Presents Table Tennis is a realistic simulation of the sport of table tennis. In the game, two players hit a ball back and forth from one another. The goal of the game is to make the opponent fail to return the ball. Players have the ability to challenge a multiplayer partner, either offline or online, or can select to challenge the game s artificial intelligence.Players can select from a roster of eleven characters, which are unlocked as they progress through the game; each character has particular skills in different areas.'),
(44, '1', '2/5', '9+', '35 min', 'The game is a side-scrolling boxing game where the player moves left and right to control a screen sized boxer. When the timing is right, the player can unleash a final blow punch which can sometimes KO the opponent in a single strike. The home versions contain a spectator mode where the player can watch their favorite boxers compete.'),
(45, '1', '1.5/5', '7+', '30 min', 'The core game is a two-dimensional, one-on-one, versus fighting game. Players take on the roles of martial artists competing in a kumite tournament. Rather than wearing down an opponent s health, the goal is instead to score single solid hits. After each hit, combat stops and both combatants are returned to their starting positions. Depending on how well players hit their opponent, they score either a half-point or a full point. Matches can be quite brief, as only two full points are required to win, and a point can be quickly scored just seconds after a round begins.'),
(46, '1', '1.5/5', '8+', '45 min', 'The bowler (on the left side of the screen) may move up and down his end of the alley to aim before releasing the ball. In four of the game s six variations, the ball can be steered before it hits the pins. Knocking down every pin on the first shot is a strike, while knocking every pin down in both shots is a spare. The player s score is determined by the number of pins knocked down in all 10 frames, as well as the number of strikes and spares acquired.'),
(47, '1', '2.5/5', '6+', '40-60 min', 'The main goal of the game is to expand and develop a city, evolving from the Stone Age to the Colonization of Mars. The city has houses that provide coins and population, production buildings that provide tools, buildings that produce goods, and decorations that provide happiness. Forge points, with a meter that refills in time, allow to research technologies, which unlock new buildings, more building space and other bonuses.'),
(48, '1-2', '1.5/5', '9+', '45 min', 'All of your buildings, units, spells, and research will need some or all of these resources. Once you build the basic level for the timber camp, quarry, and silver mine you will begin to receive those resources automatically. The rate at which you generate those resource will depend on your island type. Divine Favor will only begin to accumulate once you select a god to worship in your city. The higher the level of your Timber Camp, Quarry, Silver Mine, and Temple the more quickly you will gain resources.'),
(49, '2-3', '1.5/5', '9+', '50-60 min', 'Tribal Wars has to be played with the supported browsers over the official web versions or the official and updated mobile apps. Any kind of action in the game has to be done by hand or by a selection of permitted scripts and tools only.'),
(50, '1', '2.5/5', '6+', '25 min', 'Discover new lands and experience exciting adventures and duels! The West awaits!'),
(51, '2-3', '3/5', '10+', '45 min', 'The gameplay of both races will be pretty similar but your choice will influence some main traits: The look of your city will depend upon the race you’ve picked. Elves are magical beings, and live in close harmony with nature. Their building design will be very sophisticated. Humans are very ambitious and determined meaning they have a more medieval and industrialized style. The military units that you have at your disposal will also differ. For example, Elves will rely, amongst others, on Treants and Humans on Axe Barbarians.'),
(52, '2-4', '3.5/5', '9+', '20 min', 'The basic game can be played by two to four players, representing the activities of Spain, England, France or Portugal. The game also includes a solitaire scenario where Spain is played by a single player, and the original SPI edition included optional rules for an additional player to take a purely financial role as the German bankers.'),
(53, '2', '1/5', '7+', '20 min', 'NASCAR Heat 4 is the official video game of NASCAR. Looking and sounding better than ever with updated user interface, graphics and engine audio, race across 38 tracks in all three NASCAR National Series plus the fan-favorite Xtreme Dirt Tour.'),
(54, '1', '1.5/5', '9+', '10 min', 'Race thru the city, desert & snow! Dodge obstacles and other cars to grab power-ups & coins. Use your coins to add upgrades and unlock more races & cars. Earn extra coins on HotWheels.com to use in the game! Go for it!'),
(55, '2', '2.5/5', '9+', '20 min', 'The World of Cars Online allowed users to customize their own car, chat with other players, decorate their own yard, race against friends, and complete different quests with all of their favorite movie characters. There were also different mini games to earn coins such as Mater s Tractor Tipping.'),
(56, '2', '1/5', '6+', '20 min', ' Race down the road to the finish line as a Team Hot Wheels driver! You can compete as Gage, Brandon, Wyatt or Rhett and race in their signature vehicle, too! Avoid obstacles and collect power-ups to win each level to take the next course! Go for it!'),
(57, '4', '1.5/5', '9+', '45 min', 'To play, a player starts the game as the Pilot of the ship, controlling the direction and speed at which the ship travels, and shooting the lasers and nukes directly ahead at whatever was in the center of the screen. Incoming nukes can be avoided using the \"Hyperspace\" control.');

--
-- Indexuri pentru tabele eliminate
--

--
-- Indexuri pentru tabele `infogames`
--
ALTER TABLE `infogames`
  ADD PRIMARY KEY (`id_joc`);

--
-- AUTO_INCREMENT pentru tabele eliminate
--

--
-- AUTO_INCREMENT pentru tabele `infogames`
--
ALTER TABLE `infogames`
  MODIFY `id_joc` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
